project:
  type: website
  output-dir: docs
  
website:
  title: "" 
  navbar:
    logo: "img/alaska-logo.png"
    logo-alt: "Great State of Alaska Logo" # alt text
    left:
      - href: index.qmd
        text: Home
      - href: reports.qmd
        text: Reports
      - href: reporting_guide.qmd
        text: Reporting Guide
      - href: resources.qmd
        text: Resources
      - href: analysis_collection.qmd
        text: Methods
      - href: about.qmd
        text: About
    tools:
      - icon: facebook
        href: https://www.facebook.com/doh.alaska
        aria-label: "Visit Alaska Department of Health on Facebook"
      - icon: youtube
        href: https://www.youtube.com/alaskadhss
        aria-label: "Visit Alaska DHSS on YouTube"
      - icon: github
        href: https://github.com/AlaskaBirthDefectsRegistry/
        aria-label: "Visit Alaska Birth Defects Registry on GitHub"
  search: 
    location: navbar
    type: overlay
  page-footer:
    right: "Built with [Quarto](https://quarto.org/)"
    left: "&copy; Copyright 2025, State of Alaska Dept. of Health"
   

format:
  html:
    theme: default 
    css: |
      .navbar {
        background-color: var(--bs-primary) !important;
      }
    toc: false
    include-after-body: accessibility-fixes.html

editor: source

