project:
  type: website
  output-dir: docs
  
website:
  title: "ABDR Data Site"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: reports.qmd
        text: Reports
      - href: reporting_guide.qmd
        text: Reporting Guide
      - href: resources.qmd
        text: Resources
      - href: analysis_collection.qmd
        text: Methods
    tools:
      - icon: facebook
        href: https://www.facebook.com/doh.alaska
      - icon: youtube
        href: https://www.youtube.com/alaskadhss
      - icon: github
        href: https://github.com/AlaskaBirthDefectsRegistry/
  page-footer:
    right: "Built with [Quarto](https://quarto.org/)"
    left: "&copy; Copyright 2025, State of Alaska Dept. of Health"

format:
  html:
    theme: Flatly
    toc: true

editor: source

