---
title: "Annual_Report"
format: html
---

Prevalence Table
```{r}

#| label: chunk-label-1  
#| warning: false 
#| message: FALSE 
#| echo: false

library(epitools)
library(lubridate)  
library(RODBC)
library(dplR)
library(plyr)
library(knitr)
library(htmlTable)
library(dplyr)
library(tidyverse)

# library(datadr)                                                               # Not available for R 4.0.2

# Removing scientific notation
options(scipen=999)

channel.c<-odbcDriverConnect("Driver={Microsoft Access Driver (*.mdb, *.accdb)};
                             DBQ=R:\\ABDR\\Analysis_New\\ABDR_CASECONF\\CaseConfProb.accdb")
CPROB<-sqlQuery(channel.c,"SELECT * FROM CaseConfProb1")

load("R:\\ABDR\\Research_Data_tables\\ResearchTables2007_2022\\ABDR_BTH_0722RSRCH_L3.Rda") # #

A_Y5<-subset(ABDR_BTH_0722RSRCH_L3,year(dob) %in% (2018:2022))                  # # #


key<-sqlQuery(channel.c,"SELECT * FROM CODES")


#### Organize data ####
#Cleft lips
 # A_Y5$CLP.1<-with(A_Y5,ifelse(CLP==1,1,ifelse(CL==1 & CP==1,1,0)))
 # A_Y5$CL.1<-with(A_Y5,ifelse(CL==1 & CP==1 & CLP==1,0,
 #                      ifelse(CL==1 & CP==1 & CLP==0,0,
 #                      ifelse(CL==1 & CP==0 & CLP==1,0,
 #                      ifelse(CL==1 & CP==0 & CLP==0,1,0)))))
 # A_Y5$CP.1<-with(A_Y5,ifelse(CL==1 & CP==1 & CLP==1,0,
 #                      ifelse(CL==1 & CP==1 & CLP==0,0,
 #                      ifelse(CL==0 & CP==1 & CLP==1,0,
 #                      ifelse(CL==0 & CP==1 & CLP==0,1,0)))))
 #drop Cleft reports to add in new ones
  ###These are mutually exclusive now!!!!
A_Y5 <-A_Y5 %>%
  mutate(CL.1 = ifelse(CL == 1, 1, 0)) %>%
  mutate(CP.1 = ifelse(CP == 1, 1, 0)) %>%
  mutate(CLP.1 = ifelse(CLP == 1, 1, 0))
A_Y5 <- A_Y5 %>% select(-c(CL, CP, CLP)) %>%
  rename("CL" = CL.1, "CP" = CP.1, "CLP" = CLP.1)


A_Y5 <- A_Y5 %>%
  select(-CLOE) %>%
  rename("CLOE" = count.CLOE)
  
reports <- A_Y5 %>% 
  summarise_at(.vars = vars(ASD:CCAT, RLIA:CLP),
               .funs = sum) %>%
  data.frame() %>% 
  gather(value = "Reports")
rownames(reports) <- reports[,1] 
reports <- select(reports, -key)

reports_M <- A_Y5 %>% filter(sex == "Male") %>% 
  summarise(Reports = sum(HYP))
rownames(reports_M) <- "HYP" 

reports_F <- A_Y5 %>% 
  filter(sex == "Female") %>% 
  summarise(Reports = sum(TURN))
rownames(reports_F) <- "TURN" 

reports<-rbind(reports,reports_M,reports_F)

#Counts of births total (bts) males (btsM) and females (btsF)
  bts<- length(A_Y5$BC)
  btsM<-sapply(subset(A_Y5, sex=="Male")[1],length)
  btsF<-sapply(subset(A_Y5, sex=="Female")[1],length)

#### Prevalence For most groups ####
#Reported Prevalence
rname<-rownames(reports) 
ev1<-pois.exact(reports[c(1:45),],bts)
  ev1$NatCond<-rname[c(1:45)]
  #For Turner Syndrome#
  ev1a<-pois.exact(reports[47,],btsF)
  ev1a$NatCond<-rname[47]
ev1<-rbind(ev1,ev1a) 

# Weights
  cp<-subset(CPROB,NatCond!="HYPOS" ,select=c("NatCond","ReportsSens","Confirmed","PPV","NPV"))
    cp$NatCond<-as.character(cp$NatCond)
    cp$NatCond[cp$NatCond=="ANENC"]<-"ANEN"
    cp$NatCond[cp$NatCond=="GASTR"]<-"GAS"
    cp$NatCond[cp$NatCond=="OMPHA"]<-"OMP"
    cp <- cp[-13, ]                                                             # Removed CF
  cp1<-merge(ev1, cp, by.x = "NatCond", by.y = "NatCond",all.y=T)
# estimated Prevalence
temp1<-((as.numeric(cp1$rate))*cp1$PPV)+((1-(as.numeric(cp1$rate)))*(1-cp1$NPV))
#temp1 <- as.vector(na.omit(temp1))
temp1_logical <- is.na(temp1)
temp1[temp1_logical] <- 0
 cp2<-pois.exact(temp1*bts, bts)                                                # pois.exact() doesn't seem to like NA's but
  cp3<-cbind(cp1[,c(1,10:11)],cp2)                                              # row numbers don't line up with na.omit(temp1)
# Table
Prev<-merge(ev1,cp3[,-c(5,9)],by.x = "NatCond", by.y = "NatCond",all.x = T)
Prev1<-Prev[,-c(7)]  
  colnames(Prev1)<-c("NatCond","Reports","Births","RptPrev","RptLower","RptUpper","PPV","NPV","Defects","Prev","PrevLower","PrevUpper")

#### Prevalence For Hypospadias  ####
ev2<-pois.exact(reports[46,],btsM)
  ev2$NatCond<-rname[46]

# Weights
  hp<-subset(CPROB,NatCond=="HYPOS",select=c("NatCond","ReportsSens","Confirmed","PPV","NPV"))
      hp$NatCond<-as.character(hp$NatCond)
      hp$NatCond[hp$NatCond=="HYPOS"]<-"HYP"
  hp1<-merge(ev2, hp, by.x = "NatCond", by.y = "NatCond",all.y=T)
# estimated Prevalence
temp2<-((as.numeric(hp1$rate))*hp1$PPV)+((1-(as.numeric(hp1$rate)))*(1-hp1$NPV))
 hp2<-pois.exact(temp2*btsM,btsM)
  hp3<-cbind(hp1[,c(1,10:11)],hp2)
# Table
PrevH<-merge(ev2,hp3[,-c(5,9)],by.x = "NatCond", by.y = "NatCond",all.x = T)
Prev1H<-PrevH[,-c(7)]  
  colnames(Prev1H)<-c("NatCond","Reports","Births","RptPrev","RptLower","RptUpper","PPV","NPV","Defects","Prev","PrevLower","PrevUpper")


### Create Table for annual estimates ####
PrevTab<-rbind(Prev1,Prev1H)  
    PrevTab[,c(4:6,10:12)]<-round(PrevTab[,c(4:6,10:12)]*10000,1)
    PrevTab[,c(7,8)]<-round(PrevTab[,c(7,8)],4)
    PrevTab[,9]<-round(PrevTab[,9],1)
  PrevTab[,c(4:12)]<-format(PrevTab[,c(4:12)],drop0trailing = FALSE,trim = T)
PrevTab<- merge(key[,c(1,2)], PrevTab, by.x = "D_Code", by.y = "NatCond",all.y=T)# combine with descriptors

#Numbers supressed 
PrevTab$RCIa<-paste(PrevTab[,5],paste("(",PrevTab[,6],",",PrevTab[,7],")",sep = ""))
PrevTab$PCIa<-paste(PrevTab[,11],paste("(",PrevTab[,12],",",PrevTab[,13],")",sep = ""))

PrevTab1<-subset(PrevTab,select=c(D_Code,Defect,Reports,Births,RCIa,PPV,NPV,Defects,PCIa))

colnames(PrevTab1)<-c("Code","Defect","Reports","Births","Report Prevalence (95%CI)","PPV","NPV","Estimated Defects","Defect Prevalence (95%CI)")

#PrevTab1[PrevTab1$Reports<6,c(3:5)]<-'-'
PrevTab1[,6:8][PrevTab1[,6:8]=="NA"]<-""
PrevTab1[,9][PrevTab1[,9]=="NA (NA,NA)"]<-"NA"
PrevTab1<-PrevTab1[order(PrevTab1$Defect),]
PrevTab1<-PrevTab1[,-c(1,4)]

row.names(PrevTab1)<-PrevTab1[,1]
  rownames(PrevTab1)[rownames(PrevTab1)=='Turner syndrome']<-'Turner syndrome*'
  rownames(PrevTab1)[rownames(PrevTab1)=="Hypospadias"]<-"Hypospadias**"
  rownames(PrevTab1)[rownames(PrevTab1)== "Cleft lip with celft palate"] <-  "Cleft lip with celft palate***"                             
  rownames(PrevTab1)[rownames(PrevTab1)== "Cleft lip alone"] <-  "Cleft lip alone***"
  rownames(PrevTab1)[rownames(PrevTab1)== "Cleft palate alone"] <-  "Cleft palate alone***"
  rownames(PrevTab1)[rownames(PrevTab1)== "Inerrupted aortic arch"] <-  "Interrupted aortic arch"
  rownames(PrevTab1)[rownames(PrevTab1)== "Total anomalous pulmonary venous sonnection"] <-  "Total anomalous pulmonary venous connection"
PrevTab1$order<-c(17,27,26,1,2,3,29,33,44,46,45,47,34,38,4,5,28,35,39,21,40,6,
                  7,19,30,41,20,8,36,9,42,43,10,31,37,11,32,18,12,13,14,15,22,23,
                  24,25,16)
PrevTab2<-PrevTab1[order(PrevTab1$order),]
PrevTab3<-PrevTab2[,-c(1,8)]

prevtab4 <- PrevTab3 %>%
  rownames_to_column(var = "condition") %>%
  filter(`Defect Prevalence (95%CI)` != "NA") %>%
  select(condition, Reports, PPV, `Defect Prevalence (95%CI)`) %>%
  mutate(PPV = as.numeric(PPV))

#### ####
# Having to impute cleft condition values
# load("R:\\ABDR\\chris_analysis\\cleft\\ev2_cl.Rda")                           
# load("R:\\ABDR\\chris_analysis\\cleft\\ev2_cp.Rda")                           
# load("R:\\ABDR\\chris_analysis\\cleft\\ev2_clp.Rda")                           
# 
# #### CL
# cl15 <- ev2_cl %>% filter(yrs %in% 2018:2022) %>%                             # #
#   select(-c('Prevalence (95% CI)', yrs)) %>%
#   mutate_all(.funs = as.numeric) %>%
#   summarise_all(.funs = sum)
# cl15b <- cl15/5
# 
# # Pasting brackets around the upper and lower confidence intervals
# cl15b$`Defect Prevalence` <- 
#   paste(cl15b$`Defect Prevalence`, " ")
# cl15b$`Defect Prevalence` <- gsub(" ", "", cl15b$`Defect Prevalence`) %>%
#     str_pad(side = "right",width = 5)
# 
# cl15b$UpperCI <- 
#   paste(cl15b$UpperCI,")")
# cl15b$UpperCI <- gsub(" ", "", cl15b$UpperCI)
# 
# cl15b$LowerCI <- 
#   paste("(",cl15b$LowerCI,",")
# cl15b$LowerCI <- gsub(" ", "", cl15b$LowerCI) %>%
#     str_pad(side = "right",width = 6)
# 
# # Combining prevalence and confidence intervals into a single column
# cl15c <- cl15b %>% 
#   unite('Defect Prevalence (95%CI)', `Defect Prevalence`, LowerCI, UpperCI,
#         sep = " ")
# 
# #### Report Prevalence CL
# cl15_rpt <- pois.exact(cl15c[1], cl15c[3])
# cl15_rptb <- round(cl15_rpt*10000,1)
# 
# # Pasting brackets around the upper and lower confidence intervals
# cl15_rptb$rate <- 
#   paste(cl15_rptb$rate,".0", " ")
# cl15_rptb$rate <- gsub(" ", "", cl15_rptb$rate) %>%
#     str_pad(side = "right",width = 6)
# 
# cl15_rptb$upper <- 
#   paste(cl15_rptb$upper,")")
# cl15_rptb$upper <- gsub(" ", "", cl15_rptb$upper)
# 
# cl15_rptb$lower <- 
#   paste("(",cl15_rptb$lower," ")
# cl15_rptb$lower <- gsub(" ", "", cl15_rptb$lower) %>%
#     str_pad(side = "right",width = 5)
# 
# # Combining prevalence and confidence intervals into a single column
# cl15_rptc <- cl15_rptb %>% 
#   unite('Reort Prevalence (95%CI)', rate, lower, upper,
#         sep = " ")
# 
# 
# #### CP
# cp15 <- ev2_cp %>% filter(yrs %in% 2018:2022) %>%                               # #
#   select(-c('Prevalence (95% CI)', yrs)) %>%
#   mutate_all(.funs = as.numeric) %>%
#   summarise_all(.funs = sum)
# cp15b <- cp15/5
# 
# # Pasting brackets around the upper and lower confidence intervals
# cp15b$`Defect Prevalence` <- 
#   paste(cp15b$`Defect Prevalence`," ")
# cp15b$`Defect Prevalence` <- gsub(" ", "", cp15b$`Defect Prevalence`) %>%
#     str_pad(side = "right",width = 5)
# 
# cp15b$UpperCI <- 
#   paste(cp15b$UpperCI,")")
# cp15b$UpperCI <- gsub(" ", "", cp15b$UpperCI)
# 
# cp15b$LowerCI <- 
#   paste("(",cp15b$LowerCI,","," ")
# cp15b$LowerCI <- gsub(" ", "", cp15b$LowerCI) %>%
#     str_pad(side = "right",width = 6)
# 
# # Combining rpt_prev and confidence intervals into a single column
# cp15c <- cp15b %>% 
#   unite('Defect Prevalence (95%CI)', `Defect Prevalence`, LowerCI, UpperCI,
#         sep = " ")
# 
# # Report Prevalence CP
# cp15_rpt <- pois.exact(cp15c[1], cp15c[3])
# cp15_rptb <- round(cp15_rpt*10000,1)
# 
# # Pasting brackets around the upper and lower confidence intervals
# cp15_rptb$rate <- 
#   paste(cp15_rptb$rate," ")
# cp15_rptb$rate <- gsub(" ", "", cp15_rptb$rate) %>%
#     str_pad(side = "right",width = 5)
# 
# cp15_rptb$upper <- 
#   paste(cp15_rptb$upper,")")
# cp15_rptb$upper <- gsub(" ", "", cp15_rptb$upper)
# 
# cp15_rptb$lower <-
#   paste("(",cp15_rptb$lower,","," ")
# cp15_rptb$lower <- gsub(" ", "", cp15_rptb$lower) %>%
#     str_pad(side = "right",width = 6)  
# 
# # Combining prevalence and confidence intervals into a single column
# cp15_rptc <- cp15_rptb %>% 
#   unite('Reort Prevalence (95%CI)', rate, lower, upper,
#         sep = " ")
# 
# 
# #### CLP
# clp15 <- ev2_clp %>% filter(yrs %in% 2018:2022) %>%                             # #
#   select(-c('Prevalence (95% CI)', yrs)) %>%
#   mutate_all(.funs = as.numeric) %>%
#   summarise_all(.funs = sum)
# clp15b <- clp15/5
# 
# # Pasting brackets around the upper and lower confidence intervals
# clp15b$`Defect Prevalence` <- 
#   paste(clp15b$`Defect Prevalence`," ") 
# clp15b$`Defect Prevalence` <- gsub(" ", "", clp15b$`Defect Prevalence`) %>%
#     str_pad(side = "right",width = 5) 
# 
# clp15b$UpperCI <- 
#   paste(clp15b$UpperCI,")")
# clp15b$UpperCI <- gsub(" ", "", clp15b$UpperCI)
# 
# clp15b$LowerCI <- 
#   paste("(",clp15b$LowerCI,","," ")
# clp15b$LowerCI <- gsub(" ", "", clp15b$LowerCI) %>%
#     str_pad(side = "right",width = 6)     
# 
# # Combining rpt_prev and confidence intervals into a single column
# clp15c <- clp15b %>% 
#   unite('Defect Prevalence (95%CI)', `Defect Prevalence`, LowerCI, UpperCI,
#         sep = " ")
# 
# # Report Prevalence CLP
# clp15_rpt <- pois.exact(clp15c[1], clp15c[3])
# clp15_rptb <- round(clp15_rpt*10000,1)
# 
# # Pasting brackets around the upper and lower confidence intervals
# clp15_rptb$rate <- 
#   paste(clp15_rptb$rate," ")
# clp15_rptb$rate <- gsub(" ", "", clp15_rptb$rate) %>%
#     str_pad(side = "right",width = 5) 
# 
# clp15_rptb$upper <- 
#   paste(clp15_rptb$upper,")")
# clp15_rptb$upper <- gsub(" ", "", clp15_rptb$upper)
#     # str_pad(side = "right",width = 6) 
# 
# clp15_rptb$lower <- 
#   paste("(",clp15_rptb$lower,","," ")
#   clp15_rptb$lower <- gsub(" ", "", clp15_rptb$lower) %>%
#     str_pad(side = "right",width = 6)                                           
# 
# # Combining prevalence and confidence intervals into a single column
# clp15_rptc <- clp15_rptb %>% 
#   unite('Reort Prevalence (95%CI)', rate, lower, upper,
#         sep = " ")
# 
# Report_Prevalence <- c(cl15_rptc$`Reort Prevalence (95%CI)`, 
#                        cp15_rptc$`Reort Prevalence (95%CI)`, 
#                        clp15_rptc$`Reort Prevalence (95%CI)`)
# 
# Defect_Prevalence <- c(cl15c$`Defect Prevalence (95%CI)`,
#                        cp15c$`Defect Prevalence (95%CI)`, 
#                        clp15c$`Defect Prevalence (95%CI)`)
# 
# 
# clft_prevs <- data.frame(Report_Prevalence, Defect_Prevalence, 
#                          row.names = c("CL", "CP", "CLP"))
# 
# clft_prevs <- clft_prevs %>% mutate_all(.funs = as.character)
# 
# #save(clft_prevs, file = "R:/ABDR/Analysis_New/Published Data/clft_prevs.Rda")
# 
# # Replacing auto-calculated cleft conditions with more complex adjustment
# PrevTab4 <- PrevTab3
# PrevTab4[45, 2] <- clft_prevs[3, 1] 
# PrevTab4[45, 6] <- clft_prevs[3, 2]
# 
# PrevTab4[46, 2] <- clft_prevs[1, 1]
# PrevTab4[46, 6] <- clft_prevs[1, 2]
# 
# PrevTab4[47, 2] <- clft_prevs[2, 1]
# PrevTab4[47, 6] <- clft_prevs[2, 2] 
# 
# PrevTab4[22, 6] <- "-"
# 
# 
# 
# #### Make HTML Table
# tmp1<-htmlTable(PrevTab4,
#                 rgroup=c("Cardiovascular","Central Nervous System","Chromosomal","Ear","Eye","Gastrointestinal","Genitourinary","Musculoskeletal","Orofacial"),
#                 n.rgroup=c(16,4,5,1,2,4,5,6,4),
#                 col.rgroup=c("#F7F7F7","none"),
#                 rowlabel="Defect",
#                 css.cell="padding-left: 2em; padding-right: 2em;",
#                 tfoot=txtMergeLines("Ref: NA = Information not available as of publication; '-' = supressed for cell counts <6; 95% CI = 95% Confidence Interval; g = grams, PPV = Positive Predictive Value; NPV = Negative Predictive value","*per 10,000 live female births","**per 10,000 live male births", "***All cleft condition defect estimates include additional adjustments (not displayed here) for intra-conditional misclassification (i.e. individuals reported for the wrong, or multiple cleft conditions)"))
# gsub('<td','<td nowrap="nowrap";',tmp1) #removes wrapping
# 
# #library(knitr)
# # kable(PrevTab1,format="markdown",align='c',row.names = FALSE) 

```


```{r}

#| label: chunk-label-2  
#| warning: false 
#| message: FALSE 
#| echo: false

library(epitools)
library(lubridate)  
library(RODBC)
library(dplR)
library(plyr)
library(knitr)
library(pander)
library(htmlTable)
library(haven)
library(dplyr)
library(tidyverse)
library(broom)
library(DT)
library(sparkline)

# Removing scientific notation
options(scipen=999)

# Loading trend table from Access database just for defect decriptions
channel.c<-odbcDriverConnect("Driver={Microsoft Access Driver (*.mdb, *.accdb)};
                             DBQ=R:\\ABDR\\Analysis_New\\ABDR_CASECONF\\CaseConfProb.accdb")
tnd<-sqlQuery(channel.c,"SELECT * FROM Trend")

# Loading research dataset
load("R:\\ABDR\\Research_Data_tables\\ResearchTables2007_2022\\ABDR_BTH_0722RSRCH_L3.Rda") # #

gg <- ABDR_BTH_0722RSRCH_L3 %>%                                                 #
  mutate(YOB = ifelse(is.na(dob), 
                      substr(BC, start = 0, stop = 4), 
                      year(ymd(dob))))
ABDR_L3 <- gg %>%
  select(HYP:YOB) %>%
  group_by(YOB) %>%
  summarise_all(.funs = sum) %>%
  filter(YOB %in% 2018:2022)                                                    #
                           
# Loading Birth Certificate data
load("R:\\ABDR\\Research_Data_tables\\ResearchTables2007_2022\\bth07_22.Rda")   # #
                           
# Loading ABDR data with NatCond variable
load("R:\\ABDR\\Research_Data_tables\\ResearchTables2007_2022\\ABDR_0722YOR_YOB.Rda") # #

ABDR_YOB <- ABDR_0722YOR_YOB %>%                                                #
  distinct(BC, NatCond, YOB) %>%
  group_by(NatCond, YOB) %>%
  dplyr::summarise(cases = n())

# #### Loading  BVS data (MCH Unit specific) ####
birth<-read_sas("R:\\ResData\\BVS MASTER FILES\\AUTHORIZED RESEARCHERS ONLY\\current\\birth_statistical.sas7bdat")

birth2 <- birth %>%
  select(birth_cert, dob, sex)
#

# fp_vs2 <- file.path("R:\\ResData\\BVS MASTER FILES\\AUTHORIZED RESEARCHERS ONLY\\current\\_89_birth.sas7bdat")
# BVS89 <- read_sas(fp_vs2) # Births from 1990-2012
# 
# fp_vs <- file.path("R:\\ResData\\BVS MASTER FILES\\AUTHORIZED RESEARCHERS ONLY\\current\\_03_birth.sas7bdat")
# BVS03 <- read_sas(fp_vs) # Births from 2013-2019
# 
# BVS89_2 <- BVS89 %>% 
#   dplyr::select(birth_certificate_number, child_dob, SEX)
# BVS03_2 <- BVS03 %>% 
#   dplyr::select(birth_certificate_number, child_dob, sex)
# 
# colnames(BVS89_2) <- c("birth_certificate_number", "child_dob", "sex")
# 
# # Combing both BVS datasets (BVS89_2 and BVS03_2) into one dataset (BVS) 
# BVS <- rbind(BVS89_2, BVS03_2)

# Creating a year of birth varible (YOB)
birth3 <- birth2 %>% mutate(YOB = ifelse(is.na(dob), 
                                    substr(birth_certificate_number, 
                                           start = 0, stop = 4), 
                                    year(ymd(dob))))

# Creating dataframe of birth per year (birth_totals)
birth_totals <- birth %>% 
  filter(dob_yr %in% 2018:2022) %>%                                             #
  dplyr::group_by(dob_yr) %>% 
  dplyr::summarise(total_population = n()) %>%
  mutate_all(.funs = as.integer) %>%
  dplyr::rename("YOB" = dob_yr)

# Creating dataframe of female birth per year (f_birth_totals)
f_birth_totals <- birth %>%
  filter(sex == "F") %>% 
  filter(dob_yr %in% 2018:2022) %>%                                             #
  dplyr::group_by(dob_yr) %>% 
  dplyr::summarise(female_population = n()) %>%
  mutate_all(.funs = as.integer) %>%
  dplyr::rename("YOB" = dob_yr)

# Creating dataframe of male birth per year (m_birth_totals)
m_birth_totals <- birth %>%
  filter(sex == "M") %>% 
  filter(dob_yr %in% 2018:2022) %>%                                             #
  dplyr::group_by(dob_yr) %>% 
  dplyr::summarise(male_population = n()) %>%
  mutate_all(.funs = as.integer) %>%
  dplyr::rename("YOB" = dob_yr)

# Joining birth_totals with ABDR
ABDR_2 <- dplyr::left_join(ABDR_YOB, birth_totals, by = "YOB") %>% 
  merge(f_birth_totals, by = "YOB") %>%
  merge(m_birth_totals, by = "YOB") %>%
  arrange(NatCond, YOB)

# Identify conditions with < 3 occurrences and exclude
ABDR_3 <- ABDR_2 %>% 
  filter(!is.na(NatCond))

# Altering ABDR_3 denominators (total_population) to only female births for TURN
#and only male births for HYP: ABDR_4
ABDR_4 <- ABDR_3 %>%
  mutate(total_population = if_else(NatCond == "HYP", 
                                    male_population,
                                    if_else(NatCond == "TURN", 
                                            female_population,
                                    total_population))) %>%
  filter(YOB > 2017)                                                            # Add one year

# Creating a funciton to run glm model
yob_model <- function(df) {
  glm(glm(cases ~ YOB,
                 family=quasipoisson(link="log"),
                 offset=log(total_population),
                 data = df))
}

# Creating dataframe with p-values: pval
# Running a glm model for each National Condition and "tidying" outputs
models <- ABDR_4 %>% 
  dplyr::group_by(NatCond) %>% 
  nest() %>%
  mutate(model_a = map(data, yob_model)) %>%
  dplyr::summarise(tdy = purrr::map_df(.x = model_a, 
                                .f = broom::tidy, 
                                .id = "model"))

# Binding columns from models dataframe to produce tibble and renaming columns
models2 <- bind_cols(models$NatCond, models$tdy) %>%
  rename("NatCond" = `...1`)

# Filtering by year of birth and select NatCond and a rounded p-value.
pval <- models2 %>%
  filter(term == "YOB") %>%
  select(NatCond, p.value) %>%
  mutate(p.value = round(p.value, digits = 2))

# Creating annual rates for each condition: rts
rts<-ddply(ABDR_4,.(NatCond,YOB),summarise,Rate=(cases/total_population)*10000) 

# Reshaping rts to a wide format
rts1<-reshape(rts,timevar="YOB",idvar="NatCond",direction="wide")

#Reordering variables
rts1 <- rts1[c("NatCond",# "Rate.2007", "Rate.2008", "Rate.2009", "Rate.2010", 
      # "Rate.2011", "Rate.2012", "Rate.2013", "Rate.2014", "Rate.2015",
      # "Rate.2016", "Rate.2017", 
      "Rate.2018", "Rate.2019", "Rate.2020", 
       "Rate.2021", "Rate.2022")]                                               #

# Merging rts1 and pval2 into one dataframe: trend
trend<-merge(rts1,pval,by="NatCond",all.x=T)    

# Creating a column of number of years used in the model
cond <- ddply(ABDR_4,.(NatCond),summarise,Cases=length(cases)) 

# Creating a dataframe of NatCond matched with Defect descripiton: cond_b
cond_b <- cond %>% 
  left_join(tnd, by = c("NatCond" = "D_Code")) %>%
  distinct(NatCond, Defect)

# Combining the number of years used in each model to trend(w/o the NatCond)
trend1 <- merge(trend, cond_b, by = "NatCond") %>% 
  mutate(NatCond = Defect) %>% 
  select(-Defect)

colnames(trend1) <-c("Defect", #"2007", "2008", "2009", "2010", "2011", "2012", 
                    # "2013", "2014", "2015", "2016", "2017",
                     "2018", "2019", "2020", "2021", "2022", "p-value")                         #

trend1[,2:6]<-round(trend1[,2:6],1)                                             # # add one to all last column numbers
trend1[,7]<-round(trend1[,7],4)                                               # #
trend1[,2:6]<-format(trend1[,2:6],drop0trailing = FALSE,trim = T)             # #
trend1[,2:6][trend1[,2:6]=="NA"|trend1[,2:6]=="NaN"]<- 0 # used to be "-" not zero   # # #

row.names(trend1)<-trend1[,1]

# Creating a list of ordered Defects
s <- c("Aortic valve stenosis", 
       "Atrial septal defect", 
       "Atrioventricular septal defect", 
       "Coarctation of the aorta", "Common truncus", 
       "Double outlet right ventricle", "Ebstein anomaly", 
       "Hypoplastic left heart syndrome", "Inerrupted aortic arch", 
       "Pulmonary valve atresia and stenosis", "Single ventricle", 
       "Teratology of fallot", "Total anomalous pulmonary venous connection", 
       "Transposition of the great arteries", 
       "Tricuspid valve atresia and stenosis", 
       "Ventricular septal defect", "Anencephalus", 
       "Spina bifida without anencephalus", "Encephalocele", 
       "Holoprosencephaly", "Deletion 22 q11", "Trisomy 13", "Trisomy 18", 
       "Trisomy 21 (Down syndrome)", "Turner syndrome", "Anotia / microtia", 
       "Anophthalmia / microphthalmia", "Congenital cataract", 
       "Biliary atresia", "Esophageal atresia / tracheoesophageal fistula", 
       "Rectal and large intestinal atresia / stenosis",
       "Small intestinal atresia / stenosis", "Bladder exstrophy", 
       "Congenital posterior urethral valves", "Hypospadias", 
       "Renal agenesis / hypoplasia", "Clubfoot", "Craniosynostosis", 
       "Diaphragmatic hernia", "Gastroschisis", "Limb deficiencies", 
       "Omphalocele", "Choanal atresia", "Cleft lip with celft palate",
       "Cleft lip alone", "Cleft palate alone")

# Setting s as a factor to obtain levels
s <- as.factor(s)

# Reodering trend1 by the levels of s; trend2
trend2 <- trend1 %>% 
  mutate(Defect = factor(Defect, levels = s)) %>%
  arrange(Defect) %>%
  mutate(Defect = as.character(Defect))

# Adding '*' to Turner Syndrome and Hypospadias
trend2$Defect[trend2$Defect == 'Turner syndrome'] <- 'Turner syndrome*'
trend2$Defect[trend2$Defect == "Hypospadias"] <-"Hypospadias**"

# Setting variable "Defect" to row names and dropping Defect
#row.names(trend2) <- trend2$Defect
trend2 <- trend2 %>% select(-Defect)


tidytrend <- trend2 %>%
  rownames_to_column() %>%
  select(-`p-value`) %>%
  pivot_longer( names_to = "year", values_to = "reports", `2018`:`2022`) %>%    #
  mutate(reports = ifelse(reports == "-", 0, reports)) %>%
  mutate(reports = as.numeric(reports), 
         year = as.numeric(year)) %>%
  rename("condition" = rowname) %>%
  left_join(prevtab4, by = "condition") %>%
  select(-c(Reports,`Defect Prevalence (95%CI)`)) %>%
  filter(!(is.na(PPV))) %>%
  mutate(reports = round(reports*PPV, 2)) 

sparkline_data <- tidytrend %>%
  dplyr::group_by(condition) %>%
  dplyr::summarize(
    TrendSparkline = spk_chr(
      reports, type ="line",
      chartRangeMin = 0, chartRangeMax = max(reports)
    )
  )


trend3 <- trend2 %>%
  mutate(de_groups = c("Cardiovascular", "Cardiovascular", "Cardiovascular", 
                       "Cardiovascular", "Cardiovascular", "Cardiovascular", 
                       "Cardiovascular", "Cardiovascular", "Cardiovascular", 
                       "Cardiovascular", "Cardiovascular", "Cardiovascular",
                       "Cardiovascular", "Cardiovascular", "Cardiovascular",
                       "Cardiovascular",
                       "Central Nervous System", "Central Nervous System", 
                       "Central Nervous System", "Central Nervous System", 
                       "Chromosomal", "Chromosomal", "Chromosomal", 
                       "Chromosomal", "Chromosomal", "Ear", "Eye", "Eye", 
                       "Gastrointestinal", "Gastrointestinal", 
                       "Gastrointestinal", "Gastrointestinal", "Genitourinary", 
                       "Genitourinary", "Genitourinary", "Genitourinary",
                       "Genitourinary",
                       "Musculoskeletal", "Musculoskeletal", "Musculoskeletal", 
                       "Musculoskeletal", "Musculoskeletal", "Musculoskeletal", 
                       "Orofacial", "Orofacial", "Orofacial", "Orofacial")) %>%
  rownames_to_column() %>%
  rename("condition" = rowname)

trend4 <- left_join(trend3, sparkline_data, by = "condition") %>%
  dplyr::rename("Trend" = TrendSparkline) %>%
  select(condition:`p-value`, Trend, de_groups) %>%
  column_to_rownames(var = "condition")

trend4_no_groups <- trend4 %>%
  select(-de_groups)

trend5 <- trend4 %>%
  rownames_to_column(var = "condition") %>%
  left_join(prevtab4, by = "condition") %>%
  mutate(across(.cols = c(`2018`:`p-value`), as.numeric)) %>%
  mutate(across(.cols = c(`2018`:`2022`), ~ .x*PPV)) %>%
  filter(!is.na(`2018`)) %>%
  select(-c(Reports, PPV, `Defect Prevalence (95%CI)`))  %>%
  mutate(`p-value` = ifelse(`p-value` <= 0.05, 
                            "Significant", 
                            "Not Significant")) %>%
  mutate(`p-value` = as.character(`p-value`)) %>%
  mutate(`p-value` = ifelse(is.na(`p-value`), "*", `p-value`)) %>%
  mutate(`p-value` = ifelse(`p-value` == "NaN", "*", `p-value`))

```


Joining pretab4 and trend5
```{r}

#| label: chunk-label-3  
#| warning: false 
#| message: FALSE 
#| echo: false

annual <- prevtab4 %>%
  inner_join(trend5, by = "condition")

# importing national prevalence rates
nat_prev <- read_csv("R:/ABDR/Website/ABDR_Quarto_Website/birth_defects_prevalence.csv") %>%
  rename("condition" = Diagnosis) %>%
  mutate(national_prev = paste(US_Prevalence, paste("(",`US_95%_CI`,")", sep = ""))) %>%
  select(condition, national_prev)

# Joining national prevalence stats
annual_report <- annual %>%
  left_join(nat_prev, by = "condition") %>%
  select(condition, Reports, `Defect Prevalence (95%CI)`,
         national_prev, Trend, `p-value`, de_groups) %>%
  mutate(national_prev = ifelse(national_prev == "NA (,)"
                                , NA, national_prev)) %>%
    mutate(national_prev = ifelse(national_prev == "NA (NA)"
                                , NA, national_prev)) %>%
  column_to_rownames(var = "condition")

annual_report_no_groups <- annual_report %>%
  select(-de_groups)

colnames(annual_report_no_groups) <- c("AK Reports", "AK Prevalence (95%) CI", "U.S Prevalence","5-yr Trend", "Trend")
```



```{r}
#| label: chunk-label-3
#| warning: false 
#| message: FALSE 
#| echo: false

tmp1<-htmlTable(annual_report_no_groups,
                caption = "Selected Birth Defect Counts and Prevalence (per 10,000 live births), Alaska and US(&dagger;)",
              rgroup=c("Cardiovascular","Central Nervous System",
                         "Chromosomal","Eye",
                         "Musculoskeletal"),
               css.table = "font-size: 22px;",
               n.rgroup=c(11,4,3,1,6),
              # col.rgroup=c("#F7F7F7","none"),
               rowlabel="Condition",
                css.cell="padding-left: 2em; padding-right: 2em;",
                tfoot=txtMergeLines("Ref: 95% CI = 95% Confidence Interval",
                                  #  "'-' Indicates less than 6 reports",
                                  "'*' Indicates the data exhibited excess zeros, preventing model convergence",
                                  "AK reports and prevalence estimates are based on data from 2018-2022",
                                  "U.S prevalence estimates are based on data from 2016-2020",
                                  "(&dagger;)Stallings EB, Isenburg JL, Rutkowski RE, Kirby RS, Nembhard WN, Sandidge T, Villavicencio S, Nguyen HH, McMahon DM, Nestoridi E, Pabst LJ; National Birth Defects Prevention Network. National population-based estimates for major birth defects, 2016-2020. Birth Defects Res. 2024 Jan;116(1):e2301. doi: 10.1002/bdr2.2301. PMID: 38277408; PMCID: PMC10898112."))
#gsub('<td','<td nowrap="nowrap";',tmp1) #removes wrapping

library(kableExtra)
library(webshot2)
Sys.setenv(CHROMOTE_CHROME = "C:/Program Files (x86)/Microsoft/Edge/Application/msedge.exe")
save_kable(tmp1, file = "R:/ABDR/Presentations & Abstracts/annual_report.png")
tmp1

```


```{r}

#| label: chunk-label-4
#| warning: false 
#| message: FALSE 
#| echo: false

demo_tbl <- datatable(annual_report,
                      escape = FALSE,
                      extensions = c("RowGroup"), #, "Responsive"),
          options = list(rowGroup = list(dataSrc = 6),                          # dataSrc = 6 because column 6 is the grouping variable
                         pageLength = 23, 
                         dom = 't',
                         paging = FALSE, fnDrawCallback = htmlwidgets::JS(
  '
function(){
  HTMLWidgets.staticRender();
}
'
)
       ),
          container = tmp1,
          rownames = T,
          class = 'cell-border stripe') %>%
  spk_add_deps()

demo_tbl
```

