---
title: "Reports"
---

## Rates and Trends

* [Prevalence Rates](Prevalence_current.qmd)
* [Prevalence Trends](trend_current.qmd)

## Condition Specific Reports

### Cardiovascular
* [Coarctation of the aorta](https://rpubs.com/AK_ABDR/1043607)
* [Common truncus](https://rpubs.com/AK_ABDR/1045079)
* [Double outlet right ventricle](https://rpubs.com/AK_ABDR/1043675)
* [Ebstein anomaly](https://rpubs.com/AK_ABDR/1043678)
* [Hypoplastic left heart syndrome](https://rpubs.com/AK_ABDR/1045456)
* [Interrupted aortic arch](https://rpubs.com/AK_ABDR/1043713)
* [Pulmonary valve atresia and stenosis](https://rpubs.com/AK_ABDR/1045021)
* [Single ventricle](https://rpubs.com/AK_ABDR/1045023)
* [Teratology of fallot](https://rpubs.com/AK_ABDR/1045064)
* [Total anomalous pulmonary venous Return](https://rpubs.com/AK_ABDR/1045027)
* [Transposition of the great arteries](https://rpubs.com/AK_ABDR/1045028)
* [Tricuspid valve atresia and stenosis](https://rpubs.com/AK_ABDR/1045068)

### Central Nervous System
* [Anencephaly](https://rpubs.com/AK_ABDR/1043560)
* [Anencephaly](Anencephaly_tar.qmd)
* [Spina bifida without anencephalus](https://rpubs.com/AK_ABDR/1045024)
* [Encephalocele](https://rpubs.com/AK_ABDR/1043684)

### Chromosomal
* [Trisomy 13](https://rpubs.com/AK_ABDR/1045072)
* [Trisomy 18](https://rpubs.com/AK_ABDR/1045076)
* [Trisomy 21 (Down syndrome)](https://rpubs.com/AK_ABDR/1045078)

### Eye
* [Anophthalmia/Microphthalmia](https://rpubs.com/AK_ABDR/anoph)

### Genitourinary
* [Hypospadias](https://rpubs.com/AK_ABDR/1043711)

### Musculoskeletal
* [Clubfoot](https://rpubs.com/AK_ABDR/1043609)
* [Craniosynostosis](https://rpubs.com/AK_ABDR/CR_2007-2021)
* [Diaphragmatic hernia](https://rpubs.com/AK_ABDR/1043627)
* [Gastroschisis](https://rpubs.com/AK_ABDR/1043706)
* [Limb Deficiencies](https://rpubs.com/AK_ABDR/limb)
* [Omphalocele](https://rpubs.com/AK_ABDR/1045016)

### Orofacial
* [Cleft Lip](https://rpubs.com/AK_ABDR/1043611)
* [Cleft Palate](https://rpubs.com/AK_ABDR/1043623)